services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '9999:9999'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '50MB'

  payment-01: &payment-01 # image: payment-processor:latest
    build:
      context: ../payments
      dockerfile: Dockerfile
    container_name: payment-processor-default
    hostname: payment-processor-default
    environment:
      - TRANSACTION_FEE=0.05
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=payment-processor-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - 8001:8080
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '125MB'
  payment-02:
    <<: *payment-01
    container_name: payment-processor-fallback
    hostname: payment-processor-fallback
    environment:
      - TRANSACTION_FEE=0.05
      - RATE_LIMIT_SECONDS=5
      - INITIAL_TOKEN=123
      - DB_CONNECTION_STRING=Host=payment-processor-db;Port=5432;Database=rinha;Username=postgres;Password=postgres;Minimum Pool Size=15;Maximum Pool Size=20;Connection Pruning Interval=3
    ports:
      - 8002:8080
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '125MB'
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
