services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '9999:9999'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - payment-01
      - payment-02
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '50MB'
  payment-01: &payment-01 # image: payment-processor:latest
    build:
      context: ../payments
      dockerfile: Dockerfile
    container_name: payment-01
    hostname: payment-01
    environment:
      - PORT=9999
      - BASE_URL_PAYMENT_PROCESSOR=http://payment-processor-default:8001
      - BASE_URL_PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8002
    ports:
      - 9998:9999
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '125MB'
  payment-02:
    <<: *payment-01
    container_name: payment-02
    hostname: payment-02
    environment:
      - PORT=9999
      - BASE_URL_PAYMENT_PROCESSOR=http://payment-processor-default:8001
      - BASE_URL_PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8002
    ports:
      - 9997:9999
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '125MB'
networks:
  backend:
    driver: bridge
    name: backend
  payment-processor:
    external: true
